name: Client Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build/Publish Client Docker
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          # The name of the image you would like to push
          name: jeffvalore/k8s-when-ready
          # The login username for the registry
          username: jeffvalore
          # The login password for the registry
          password: ${{ secrets.dockerHubPassword }}
          workdir: packages/k8s-when-ready-client
